project: 
  type: website
  
website: 
  page-navigation: true
  title: "NOAA Fisheries PAM-Glider Rodeo" 
  site-url: "https://nmfs-pam-glider.github.io/GliderRodeo/"
  repo-url: "https://github.com/NMFS-PAM-Glider/GliderRodeo"
  repo-actions: [edit, source, issue]
  favicon: content/figs/favicon.ico
  search: true
  
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/79/NOAA_logo.svg"
    favicon: content/figs/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://nmfs-pam-glider.github.io/GliderRodeo/
        text: "NMFS PAM-Glider Rodeo"
      - icon: github
        href: https://github.com/NMFS-PAM-Glider/GliderRodeo
        text: "PAM-Glider Rodeo Github"

    style: "docked"
    search: true
    collapse-level: 1

    contents:
      - href: index.qmd
        text: Home
      # - section: "PAM-Glider Rodeo"
        contents:
          - href: content/Survey.qmd
            text: Survey
          - href: content/Gliders.qmd
            text: Gliders
          - href: content/Metrics.qmd
            text: Metrics
          - href: content/infoSharing.qmd
            text: Information Sharing
          - href: content/contactUs.qmd
            text: Contact Us


  
format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true

 

filters:
  - include-files.lua
  - quarto

