project: 
  type: website
  output-dir: _site

website: 
  page-navigation: true
  title: "NOAA quarto simple" 
  site-url: "https://nmfs-pam-glider.github.io/GliderRodeo/" 
  repo-url: "https://github.com/NMFS-PAM-Glider/GliderRodeo"
  repo-actions: [edit, source, issue]
  favicon: content/images/GliderRodeo.png
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/79/NOAA_logo.svg"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: "https://nmfs-pam-glider.github.io/GliderRodeo/"
        text: "NOAA Fisheries PAM-Glider Rodeo"
      - icon: github
        href: "https://github.com/NMFS-PAM-Glider/GliderRodeo"
        text: "NOAA Fisheries PAM-Glider Rodeo"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: content/overview.qmd
        text: "Overview"
      - href: content/data-collection.qmd
        text: "Data Collection"
      - href: content/hardware.qmd
        text: "Hardware"
      - href: content/pre-processing.qmd
        text: "Pre-Processing"
      - section: content/hackathon.qmd
        text: "Hackathon"
      #   contents:
      #   - content/hack/details.qmd
      #   - content/hack/prep.qmd
      #   - content/hack/presentations.qmd
      #   - content/hack/projects.qmd
      #   - content/hack/reference.qmd
      - href: content/data-analysis.qmd
        text: "Data Analysis"
      - href: content/reporting.qmd
        text: "Reporting"



# resources: 
#   - output/*.svg
#   - output/*.drawio
#   - content/card-images/*
        
format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    link-external-newwindow: true


filters:
  - include-files.lua
  - quarto



  
