---
title: "Data"
format: html
---

# Data Management Plan

A draft [Data Management Plan](https://docs.google.com/document/d/12bI75Ho0-ega1G6QQIJenqn-rv5-S4ZpbXyxpyQLVUs/edit?usp=sharing) outlines the data collected and processes for managing the data (from initial data offload to preprocessing to final archive). This is a work in progress and access is limited.

# Glider Rodeo Datasets

[Link to Google Doc](https://docs.google.com/spreadsheets/d/1fyHxeri_VOFBRXGSuNiKqbW0iODNe0UmCyOPemWovsU/edit?usp=sharing) (for those with permissions) . Below is a summary of the datasets and their status.

<iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vR0vGMrpCMdvJiqVUVnYw6wNK1IcKPNhl_I72P8nifpVq-eyk6I9ToMytc0Ucx9Eo0pIiQMt7OUPtHM/pubhtml?widget=true&amp;headers=false" style="width:950px; height:500px; border: 2px solid black;">

</iframe>

::: {.callout-note appearance="simple"}
## Note about Data Processing Methods

Processing methods for the Glider Rodeo data are static (developed for this purpose and retained); however, the PAM-Glider Lab manual is considered a 'living' document and we expect the pre-processing methods to change as methods evolve. Specific methods for pre-processing vary by glider/PAM system, and are provided in the [Pre-Processing section]().
:::

## Raw Audio Data

Raw audio data is offloaded from the instrument, reformatted to FLAC using a standardized naming convention, and saved to our NOAA Fisheries Google Cloud Bucket (ggn-nmfs-pamdata-prod-1/nmfs-collaborative/2026_GliderRodeo). Data will be made publicly available via the [National Centers for Environmental Information Passive Acoustic Data Portal](https://www.ncei.noaa.gov/products/passive-acoustic-data) after an initial review by the U.S. Navy (according to a Navy-NMFS MOU) and metadata QAQC review.

Each glider/PAM system combination has a unique set of data pre-processing steps to complete, prior to data analysis. These steps include:

- *Offloading the data from the PAM system,*

- *Decompressing files,*

- *Creating LTSAs,*

- *QAQC,*

- *Decimating files (lower sample rates are useful for different analyses), and*

- *Updating the deployment tracker.*

Raw audio data is not available for analysis during the Hackathon due to limitations related to navy review. We will have data products associated with Soundscape Analysis methods available, as well as synthesized marine mammal acoustic detections (see below).

## Soundscape Analysis

Audio data was analyzed to provide Hybrid-millidecade band levels ([Martin et al 2021](https://doi.org/10.1121/10.0003324)) using [YAWN](https://github.com/JPalmerK/YAWN_functions) (Yet Another Way to implement Noise analysis).

## Marine Mammal Acoustic Detections

Due to complications beyond our control, accurate acoustic detection of cetacean species via manual and/or automated methods could not be completed prior to the Hackathon. A set of synthesized (fake!) data was provided in the data/detection folder to provide sample formatted data if a group would like to lead a project working with marine mammal acoustic data (projects developed with these synthesized datasets should be reproducible with *real* datasets in the future!).

The synthesized datasets are saved ad '**_FakeData_EventDetections.csv' and '**_FakeData_HrlyDetections.csv' for each glider.

## Environmental Data
[Environmental Data Processing](https://nmfs-pam-glider.github.io/GliderRodeo/content/data_processing/EnvData-processing.html) Methods for extracting and processing environmental data collected during glider deployments are provided for the Seaglider ([link to Agate instructions](https://sfregosi.github.io/agate/)) and Slocum ([link to ESD instructions](https://swfsc.github.io/glider-lab-manual/content/slocum-glider-data.html)). Hefring environmental is extracted from the Hefring website. Environmental data are saved as 'data/**_science_timeseries.csv' for each glider. 

## GPS Data
GPS data are identified for each glider surfacing, and estimated GPS points for the subsurface profiles are estimated. GPS data are saved as 'data/**_GPS_timeseries.csv'

## Engineering, Flight, and Profile Data
Glider engineering and profile data varies by platform (methods and output). See the detailed methods for each glider/pam system in the Pre-processing methods, below. 

## Deployment Summaries
Guidelines for creating post-mission reports that include sampling locations, acoustic effort, and glider paths can be found [here](https://nmfs-pam-glider.github.io/GliderRodeo/content/data_processing/DeploymentSummaries.html) 

## Pre-Processing Methods by Glider
Each section below links to detailed methods for each glider/pam system combination

-   [Seaglider - WISPR](https://nmfs-pam-glider.github.io/GliderRodeo/content/data_processing/seaglider-wispr.html)

-   [Slocum - WISPR 3](https://nmfs-pam-glider.github.io/GliderRodeo/content/data_processing/slocum-wispr3.html)

-   [Slocum - DMON 2](https://nmfs-pam-glider.github.io/GliderRodeo/content/data_processing/slocum-dmon2.html)

-   [Oceanscout - WISPR 6.1](https://nmfs-pam-glider.github.io/GliderRodeo/content/data_processing/oceanscout-wispr6.html)

-   [Alseamar](https://nmfs-pam-glider.github.io/GliderRodeo/content/data_processing/alseamar.html)

-   [Environmental Data Processing:](https://nmfs-pam-glider.github.io/GliderRodeo/content/data_processing/EnvData-processing.html) Methods for extracting and processing environmental data collected during glider deployments

:::{.callout-note appearance="simple"}
## Note about PreProcessing Methods
Pre-processing methods for the Glider Rodeo data are static (developed for this purpose and retained); however, the PAM-Glider Lab manual is considered a 'living' document and we expect the pre-processing methods to change as methods evolve.
:::
