---
title: "Pre-Processing"
format: html
---

Each glider/PAM system combination has a unique set of data pre-processing steps to complete, prior to data analysis. These steps include offloading the data from the PAM system, decompressing files, creating LTSAs, QAQC, decimating, and updating the deployment tracker. We've also included pre-processing methods for the Environmental Data and the Data Summaries. Prepared data is then transferred to cloud data storage via a shared NOAA Fisheries GCP bucket (ggn-nmfs-pamdata-prod-1/nmfs-collaborative/2026_GliderRodeo). 


Each section below links to detailed methods for each glider/pam system combination

-   [Seaglider - WISPR](https://nmfs-pam-glider.github.io/GliderRodeo/content/data_processing/seaglider-wispr.html)

-   [Slocum - WISPR 3](https://nmfs-pam-glider.github.io/GliderRodeo/content/data_processing/slocum-wispr3.html)

-   [Slocum - DMON 2](https://nmfs-pam-glider.github.io/GliderRodeo/content/data_processing/slocum-dmon2.html)

-   [Oceanscout - WISPR 6.1](https://nmfs-pam-glider.github.io/GliderRodeo/content/data_processing/oceanscout-wispr6.html)

-   [Alseamar](https://nmfs-pam-glider.github.io/GliderRodeo/content/data_processing/alseamar.html)

-   [Environmental Data Processing:](https://nmfs-pam-glider.github.io/GliderRodeo/content/data_processing/EnvData-processing.html) Methods for extracting and processing environmental data collected during glider deployments

-   [Deployment Summaries:](https://nmfs-pam-glider.github.io/GliderRodeo/content/data_processing/DeploymentSummaries.html) Guidelines for creating post-mission reports that include sampling locations, acoustic effort, and glider paths

:::{.callout-note appearance="simple"}
## Note about PreProcessing Methods
Pre-processing methods for the Glider Rodeo data are static (developed for this purpose and retained); however, the PAM-Glider Lab  manual is considered a 'living' document and we expect the pre-processing methods to change as methods evolve. 
:::
