---
title: "Details"
format: html
---

# Event Logistics

The Glider Rodeo Hackathon will be a fully virtual event with a lecture and tutorial block in 11am-2pm Pacific time and two group work times (East and West). Participants and projects will choose a group work time slot that works best for their team members. There is no cost for participating in the event. The times of the events are optimized for participants in UTC-4 (Eastern) to UTC-10 (Hawaii). Participants in other time zones are welcome to participate but events will be late night or early morning. [Time Zone Comparison](https://www.timeanddate.com/worldclock/converter.html?iso=20251020T140000).

No software is required as we will be using a JupyterHub (cloud computing platform) provisioned for the event. Participants and projects are welcome to use Python or R. We recommend at least one competent Python or R programmer per Project.

# Schedule

All times are in UTC-8 (Pacific Standard Time).

## Day 1 — Monday

| Time | Event | Details | Lead(s) |
|---|---|---|---|
| 7:00 - 10:30 | East Project Time | 10am to 1:30pm ET | |
| 7:00 - 7:45 | East Project Introduction | Welcome, Introductions, & Housekeeping [slides](https://docs.google.com/presentation/d/1fS9mCqvg_kWwCQ0Ud5_9uLb1CjNBw62e/present?slide=id.p1) | Ryan Vandermeulen |
| 7:45 - 8:45 | East Group Project Brainstorming (3 rotations) | | |
| 9:00 - 9:30 | East Project Pitching | 1 slide pitch | |
| 9:30 - 10:30 | East Group Project Breakout Rooms | Each project will have a breakout room and start to get organized. | |
| 10:30 - 11:00 | Break | | |
| 11:00 - 11:30 | Science Lecture | PACE Mission Overview [lectures](https://fish-pace.github.io/hackweek-2025/presentations/lectures.html) | Jeremy Werdell |
| 11:30 - 12:15 | Science Lecture | Hyperspectral Products for Fisheries Applications [lectures](https://fish-pace.github.io/hackweek-2025/presentations/lectures.html) | Ryan Vandermeulen |
| 12:15 - 12:30 | Break | | |
| 12:30 - 13:00 | Coding Tutorial 1 | Orientation for the Hackweek JupyterHub [tutorials](https://fish-pace.github.io/hackweek-2025/presentations/tutorials.html) | Eli Holmes |
| 13:00 - 14:00 | Coding Tutorial 2 | Accessing PACE data via earthaccess [tutorials](https://fish-pace.github.io/hackweek-2025/presentations/tutorials.html) | Eli Holmes |
| 14:00 - 14:30 | Break | | |
| 14:30 - 17:30 | West Project Time | 2:30pm to 5:30pm PT | |
| 14:30 - 15:15 | West Project Introduction | Welcome, Introductions, & Housekeeping [slides](https://docs.google.com/presentation/d/1fS9mCqvg_kWwCQ0Ud5_9uLb1CjNBw62e/present?slide=id.p1) | Eli Holmes |
| 15:15 - 16:00 | West Group Project Brainstorming (3 rotations) | | |
| 16:00 - 16:30 | West Project Pitching | 1 slide pitch | |
| 16:30 - 17:30 | West Group Project Breakout Rooms | Each project will have a breakout room and start to get organized. | |

## Day 2 — Tuesday

| Time | Event | Details | Lead(s) |
|---|---|---|---|
| 7:00 - 7:30 | East Tutorial | Fish-PACE Hackweek Collaboration via Git and GitHub [slides](https://docs.google.com/presentation/d/1JuS8pNoq0__TyQMsTcXvvmSO8eaxJkAcxJQIlVpM2XA/present) | Eli Holmes |
| 7:30 - 10:30 | East Project Work Time | Each project will have a breakout room. | |
| 9:00 - 10:30 | East/West Open Helpdesk with Mentors | Bring your questions and go into breakout room with a mentor | mentors |
| 10:30 - 11:00 | Break | | |
| 11:00 - 11:45 | Science Lecture | Harmful Algal Blooms and Hyperspectral Ocean Color Data [lectures](https://fish-pace.github.io/hackweek-2025/presentations/lectures.html) | Shelly Tomlinson; Sachi Mishra |
| 11:45 - 12:15 | Break | | |
| 12:15 - 13:00 | Coding Tutorial 1 | Remote Sensing Reflectance (Rrs) [tutorials](https://fish-pace.github.io/hackweek-2025/presentations/tutorials.html) | Ryan Vandermeulen |
| 13:00 - 13:15 | Break | | |
| 13:15 - 14:00 | Coding Tutorial 2 | Data Matchups [tutorials](https://fish-pace.github.io/hackweek-2025/presentations/tutorials.html) | Ryan Vandermeulen |
| 14:00 - 14:30 | Break | | |
| 14:30 - 15:00 | West Tutorial | Fish-PACE Hackweek Collaboration via Git and GitHub [slides](https://docs.google.com/presentation/d/1JuS8pNoq0__TyQMsTcXvvmSO8eaxJkAcxJQIlVpM2XA/present) | Eli Holmes |
| 15:00 - 17:30 | West Project Work Time | Each project will have a breakout room. | |

## Day 3 — Wednesday

| Time | Event | Details | Lead(s) |
|---|---|---|---|
| 7:00 - 7:30 | East Group Check-ins (Rose, Bud, Thorn) | | Ryan Vandermeulen |
| 7:30 - 10:30 | East Project Work Time | Each project will have a breakout room. | |
| 9:00 - 10:30 | East/West Open Helpdesk with Mentors | Bring your questions and go into breakout room with a mentor | mentors |
| 10:30 - 11:00 | Break | | |
| 11:00 - 11:45 | Science Lecture | Phytoplankton Community Composition from Ocean Color [lectures](https://fish-pace.github.io/hackweek-2025/presentations/lectures.html) | Sasha Kramer |
| 11:45 - 12:15 | Break | | |
| 12:15 - 13:00 | Coding Tutorial 1 | Accessing and Visualizing MOANA Data [tutorials](https://fish-pace.github.io/hackweek-2025/presentations/tutorials.html) | Ryan Vandermeulen |
| 13:00 - 13:15 | Break | | |
| 13:15 - 14:00 | Coding Tutorial 2 | Optical water classification and clustering [tutorials](https://fish-pace.github.io/hackweek-2025/presentations/tutorials.html) | Ryan Vandermeulen |
| 14:00 - 14:30 | Break | | |
| 14:30 - 15:00 | West Group Check-ins (Rose, Bud, Thorn) | | Eli Holmes |
| 15:00 - 17:30 | West Project Work Time | Each project will have a breakout room. | |

## Day 4 — Thursday

| Time | Event | Details | Lead(s) |
|---|---|---|---|
| 7:00 - 7:30 | East Group Check-ins (Rose, Bud, Thorn) | | Ryan Vandermeulen |
| 7:30 - 10:30 | East Project Work Time | Each project will have a breakout room. | |
| 9:00 - 10:30 | East/West Open Helpdesk with Mentors | Bring your questions and go into breakout room with a mentor | mentors |
| 10:30 - 11:00 | Break | | |
| 11:00 - 11:45 | Science Lecture | Optical Light Fields and Fish Behavior [lectures](https://fish-pace.github.io/hackweek-2025/presentations/lectures.html) | Christopher Haak |
| 11:45 - 12:00 | Break | | |
| 12:00 - 12:45 | Coding Tutorial 1 | Exploring Light Attenuation with Kd [tutorials](https://fish-pace.github.io/hackweek-2025/presentations/tutorials.html) | Ryan Vandermeulen |
| 12:30 - 12:45 | Break | | |
| 12:45 - 13:30 | Coding Tutorial 2 | PACE, Bio-Argo and Machine-learning [tutorials](https://fish-pace.github.io/hackweek-2025/presentations/tutorials.html) | Eli Holmes |
| 13:30 - 14:00 | Break | | |
| 14:30 - 15:00 | West Group Check-ins (Rose, Bud, Thorn) | | Eli Holmes |
| 15:00 - 17:30 | West Project Work Time | Each project will have a breakout room. | |

## Day 5 — Friday

| Time | Event | Details | Lead(s) |
|---|---|---|---|
| 7:00 - 11:00 | East & West Project Work Time | Each project will have a breakout room. | |
| 11:00 - 12:30 | Project Presentations | East & West together [schedule](https://fish-pace.github.io/hackweek-2025/projects/list_of_projects.html) | |
| 12:30 - 13:00 | Break | | |
| 13:00 - 14:00 | Project Presentations | East & West together [schedule](https://fish-pace.github.io/hackweek-2025/projects/list_of_projects.html) | |
| 14:00 - 14:15 | HackWeek Wrap-Up | | Ryan Vandermeulen; Eli Holmes |

# Team

*coming soon!*

# Jupyter Hub

*coming soon!*

# Event Code of Conduct

Guidelines to ensure we offer a hospitable and inclusive event and a list of resources for reporting violations. Although the content is similar, this event Code of Conduct should not be confused with the [Contributor Covenant Code of Conduct](https://github.com/fish-pace/hackweek-2025/blob/main/CODE_OF_CONDUCT.md) governing contributions to this JupyterBook.

## Overview

The organizers of this event are dedicated to providing a harassment-free learning experience for everyone regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, ethnicity, age or religion. We do not tolerate harassment of participants in any form. Sexual language and imagery is not appropriate for any event venues in either in-person or virtual form, including our discussion spaces. Participants (including event volunteers and organizers) violating these rules may be sanctioned or expelled from the hackweek at the discretion of the organizers.

## Definition of Harassment

Harassment includes, but is not limited to:

- Verbal comments that reinforce social structures of domination related to gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, ethnicity, age, religion.

- Sexual images in public spaces

- Deliberate intimidation, stalking, or following

- Harassing photography or recording

- Sustained disruption of talks or other events

- Inappropriate physical contact

- Unwelcome sexual attention

- Advocating for, or encouraging, any of the above behavior

## Expectations

We expect participants and instructors to act in ways that foster a supportive and welcoming learning community at all event venues and event-related social activities. We expect you to support collaboration and learning while participating in this community of practice. Hackweek organizers may take action to redress anything designed to, or with the clear impact of, disrupting the event or making the environment hostile for any participants (including unintentionally). Participants asked to stop any harassing behavior are expected to comply immediately. Failure to comply may result in the participant being expelled from the event at the discretion of the organizers.

## Reporting a violation

Harassment and other code of conduct violations reduce the value of the event for everyone. If someone makes you or anyone else feel unsafe or unwelcome, please report it as soon as possible to one of the lead hackweek organizers.
