---
title: "Information"
format: html
---

# Hackathon Lectures

The slides and recordings will be linked from this page as they become available. Download slides from the [shared drive](https://drive.google.com/drive/folders/1p_Bse9L02ogAFa7YYGKTI1AbC9WWGBUQ?usp=drive_link).

| Title | Slides | Recording |
|:------------------|:--------------------:|:-----------------------------:|
| Welcome to the Hackweek | [<i class="bi bi-eye"></i>](https://github.com/NMFS-PAM-Glider/GliderRodeo/blob/main/hackathon/slides/Welcome-GliderRodeo.pdf) | \- |
| Project Pitches | [<i class="bi bi-eye"></i>](https://github.com/NMFS-PAM-Glider/GliderRodeo/blob/main/hackathon/slides/ProjectPitch-GliderRodeo.pdf) | \- |
| The Glider Rodeo Overview | [<i class="bi bi-eye"></i>](https://github.com/NMFS-PAM-Glider/GliderRodeo/blob/main/supplement/Presentations/Rankin_UG2_presentation_May2026.pdf) | \- |
| Glider Rodeo Data | [<i class="bi bi-eye"></i>](https://github.com/NMFS-PAM-Glider/GliderRodeo/blob/main/hackathon/slides/Data-GliderRodeo.pdf) | \- |
| Working with JupyterHub & Github | [<i class="bi bi-eye"></i>](https://github.com/NMFS-PAM-Glider/GliderRodeo/blob/main/hackathon/slides/JupyterHub-Glider%20Rodeo.pdf) | \- |
| Coastwatch Resources for using Satellite Oceo Data | [<i class="bi bi-eye"></i>](https://github.com/NMFS-PAM-Glider/GliderRodeo/blob/main/hackathon/slides/CoastWatch_CaraWilson.pdf) | [<i class="bi bi-youtube"></i>](https://media.oregonstate.edu/media/t/1_29zq7uy7) |
| AQUAVIEW Data Portal | \- | [<i class="bi bi-youtube"></i>](https://media.oregonstate.edu/media/t/1_bee0ru1e) |
| Analysis of Noise from PAM-Gliders | [<i class="bi bi-eye"></i>](https://github.com/NMFS-PAM-Glider/GliderRodeo/blob/main/hackathon/slides/NoiseAnalysis_KaitlinPalmer.pdf) | [<i class="bi bi-youtube"></i>](https://media.oregonstate.edu/media/t/1_hd6tjslf) |
| More about Glider Noise | [<i class="bi bi-eye"></i>](https://github.com/NMFS-PAM-Glider/GliderRodeo/blob/main/hackathon/slides/GliderNoise_PierreCauchy.pdf) | [<i class="bi bi-youtube"></i>](https://media.oregonstate.edu/media/t/1_6a8yvafs) |
| Final Presentations | [<i class="bi bi-eye"></i>](https://nmfs-pam-glider.github.io/GliderRodeo/hackathon/projects.html) | [<i class="bi bi-youtube"></i>](https://media.oregonstate.edu/media/t/1_wl75rvu2) |

# Tutorials

| Title | Preview | Python | R |
|:-----------------|:----------------:|:-----------------:|:-----------------:|
| Comparing Glider Observations with Satellite Data | [<i class="bi bi-eye"></i>](https://coastwatch-training.github.io/tutorials/codegallery.html#cg-glider-tracks-satellite-comparison) | [<i class="bi bi-eye"></i>](%22/_code/tutorials/GliderTracks.ipynb%22%20download) | [<i class="bi bi-eye"></i>](%22/_code/tutorials/GliderTracks.Rmd%22%20download) |
| AQUAVIEW Tutorial | [<i class="bi bi-eye"></i>](https://storage.googleapis.com/aquaview-public-assets/glider-rodeo/index.html) | [<i class="bi bi-eye"></i>](https://storage.googleapis.com/aquaview-public-assets/glider-rodeo/notebook-preview.html) | [<i class="bi bi-eye"></i>](https://storage.googleapis.com/aquaview-public-assets/glider-rodeo/notebook-preview-R.html) |



# References

[Glider Rodeo Github Repository](https://github.com/NMFS-PAM-Glider/GliderRodeo) and [website](https://nmfs-pam-glider.github.io/GliderRodeo/)

Glider Rodeo Zenodo Repository

[AQUAVIEW](https://aquaview.org/)

### More Information

[NMFS Open Science JupyterHub Skills](https://nmfs-opensci.github.io/NMFSHackDays-2025/content/jhub.html)

[Fish-PACE Hackweek Info](https://fish-pace.github.io/hackweek-2025/intro.html)

Observable JS

- [Quarto & Observable JS](https://quarto.org/docs/interactive/ojs/)

- [Notebooks by Allison Horst](https://observablehq.com/@allisonhorst)

[Allison Horst Data Science Art](https://allisonhorst.com/data-science-art)

Resources shared in slack

- [Research Compendium Template](https://sael-swfsc.github.io/PAM_template_ResearchCompendium/)

- [IOOS QARTOD Real-Time Quality Control of Passive Acoustics Data](https://ioos.noaa.gov/ioos-in-action/passive-acoustics/)

- [IOOS QARTOD Real-Time Quality Control of In-Situ Current Observations](https://ioos.noaa.gov/ioos-in-action/currents/)

- [All IOOS QARTOD Manuals](https://ioos.noaa.gov/project/qartod/)

- [DCLDE Ithaca 2027](https://www.dclde.org/)

- [Underwater Glider Operations Knowledge Base](https://e-abdi.github.io/Glider-Operation-Best-Practices/)