---
title: "Preparation"
format: html
---

# What to Expect

The PAM-Glider Rodeo Hackweek will focus on applied, hands-on learning, with participants engaging in extended periods of small-group work. Our tutorials are designed to offer a broad snapshot of our data and science tools to support your applied investigations. Due to the relatively short duration of our events, we are not able to provide comprehensive, in-depth training in fundamental tools. Rather, our goal is to encourage team projects working with (or inspired by!) our glider and PAM datasets. The details of implementation will be what you work out via peer-learning (helping each other) in your project group.

## Typical Workflows and Tools 
Here are a few specific scenarios of how hackweek participants will engage with data science tools:

- Connecting to a Jupyter Notebook environment to access data, github, and R/Python.

- Accessing cloud-hosted environmental data products through Aquaview and CoastWatch.

- Explore data from the 'Glider Rodeo' with multiple glider platforms and sensors.

- Modifying code, committing it to Git and pushing changes to GitHub, for others on your team to view and edit.

- Create summaries of your project team, methods, and results for final presentation & sharing via github



## HackWeek Projects

A good hackweek project is a concrete idea that a team can flesh out in a week together. Not everyone needs to code. There is background research to do, data to find, and lots and lots of data wrangling. A big part of the fun of hackweek is working together with a group with a diverse set of interests and skills. “I’ll find some data.” “I make some maps of our study area.” “I’ll figure out how to do a boosted regression tree.” “I’ll use that tutorial we were shown and get xyz glider data” etc, etc. It is messy, but through this process you’ll learn new skills and also get to know your project team mates.

The project work is a combination of

- fleshing out a science idea that is small enough during Monday brainstorming.

- dividing up into tasks so that everyone can participate.

- coding and data wrangling on Tuesday through Thursday.

- and then Friday, frantically putting a presentation on your project and results.

See [Projects page](https://nmfs-pam-glider.github.io/GliderRodeo/hackathon/projects.html) for more information.

# Checklist

::: callout-important
## Attention!

Here is a checklist of things you need to do in advance:

\- \[ \] Create a Github Account

\- \[ \] Review material on the Glider Rodeo and Hackathon websites
:::

## Github Account

[GitHub](https://github.com/) enables us to collaborate on code across teams in a web environment. If you do not already have a GitHub account, then navigate to [GitHub](https://github.com/), enter your email address and click on the green ‘Sign up for GitHub’ button. Be sure to save your username and password somewhere for use during the hackweek. 

## Hackweek JupyterHub

We will be using a pre-provisioned compute environment for the hackweek which can be accessed via a web browser. You will not need to install anything. Please follow these instructions which will guide you through gaining access to the JupyterHub.

[Watch this video](https://youtu.be/uZ2Uy376Az8) to get an orientation on our JupyterHub.



## Pre-HackWeek Learning (Optional)

### What is Git?

[Git](https://git-scm.com/) is a version control system that many scientists use to collaborate on code.

See the [Software Carpentry Git](https://swcarpentry.github.io/git-novice/index.html){style="font-size: 11pt;"} instructions for a thorough explanation and background information.

::: callout-note
You are not required to know Git in advance of this event, but this is a great opportunity to learn all about it! [Here’s a quick introduction video from the official website](https://git-scm.com/video/what-is-git)
:::



