---
title: "Projects"
format: html
---

::: callout-important
**Final Presentations!!** The recording for our team share-out final project presentations is available [here](https://media.oregonstate.edu/media/t/1_wl75rvu2).
:::

## Glider Selection Dashboard

The goal is to develop a Glider Selection Dashboard that brings together information from the Glider Rodeo, glider manufacturers, and relevant datasets to help users determine which glider platform and configuration would be best suited for a particular mission.

**Team Members:**

Ehsan Abdi (Akvaplan-niva)

Anne Simonis (Estuary & Ocean Science Center, SFSU)

Kasey Castello (Scripps Institution of Oceanography, UC San Diego)

Héloïse Frouin-Mouy (University of Miami, NOAA SEFSC)

**Links:**

- [Glider Performance Tool](https://e-abdi.github.io/glider-performance-tool/)

- [Updated Glider Selection Dashboard Repository](https://github.com/e-abdi/glider-performance-tool)

- Prototype 📁 (hackathon) [hackathon-shared-repo/glider-selection-dashboard](https://github.com/NMFS-PAM-Glider/GliderRodeo/tree/main/hackathon/hackathon-shared-repo/glider-selection-dashboard)

```{=html}
<div style="position: relative; padding-bottom: 55.5%; height: 0; overflow: hidden;">
  <iframe src="hackathon_shared_repo/glider-selection-dashboard/glider-selection-dashboard_FinalPresentation.pdf"
          style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border: none;">
  </iframe>
</div>
```

## Noise Profiler

Noise (ambient and self-noise from glider operations) may reduce our ability to detect sounds of importance. It is therefore important to identify the conditions which yield elevated noise levels. The goal of this project is to create an automated slideshow-baed report to summarize noise levels linked to input variables of interest. This will allow the user to easily visualize which conditions contribute to elevated noise levels, and which frequency bands are most affected.

**Team Members:**

Aaron Deans (Scripps Institution of Oceanography, UC San Diego)

Julia Engdahl (Rutgers University, Center for Ocean Observing Leadership)

Liz Ferguson (Ocean Science Analytics)

Kaitlin Palmer (OAI, NOAA Pacific Islands Fisheries Science Center)

**Links:**

- Updated Noise Profiler

- Prototype 📁 (hackathon) [hackathon-shared-repo/noise-fx-calc](https://github.com/NMFS-PAM-Glider/GliderRodeo/tree/main/hackathon/hackathon-shared-repo/noise-fx-calc)

- [README](https://github.com/NMFS-PAM-Glider/GliderRodeo/tree/main/hackathon/hackathon-shared-repo/noise-fx-calc#readme)

```{=html}
<div style="position: relative; padding-bottom: 55.5%; height: 0; overflow: hidden;">
  <iframe src="hackathon_shared_repo/noise-fx-calc/PAM-Glider%20Noise%20Profiler%20Final%20Presentation.pdf"
          style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border: none;">
  </iframe>
</div>
```

## PAM Transform Visualizer

Passive Acoustic Monitoring (PAM) data often requires analysts to add one or more transforms to the raw audio data. The impact of transform settings and the cumulative effect of multiple transforms on the data is not intuitive. The goal of this project is to develop a visualization tool to understand the impact of one or more transforms to the original audio data. This tool will be beneficial to new (and experienced!) analysts and can serve as an educational tool.

**Team Members:**

Aaron Mau (Voice of the Ocean)

Brijonnay Madrigal (Scripps Institution of Oceanography, UC San Diego)

Ivia Closset (Finnish Meteorological Institute)

**Links:**

- Updated PAM Transform Visualizer

- Prototype 📁 (hackathon) [hackathon-shared-repo/pam-visualizer](https://github.com/NMFS-PAM-Glider/GliderRodeo/tree/main/hackathon/hackathon-shared-repo/pam-visualizer)

- [README](https://github.com/NMFS-PAM-Glider/GliderRodeo/blob/main/hackathon/hackathon-shared-repo/pam-visualizer/README.md)

```{=html}
<div style="position: relative; padding-bottom: 55.5%; height: 0; overflow: hidden;">
  <iframe src="hackathon_shared_repo/hackathon-shared-repo/blob/main/pam-visualizer/transformer-viz_Presentation_09182026.pdf"
          style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border: none;">
  </iframe>
</div>
```

## Noise Nowcaster

Ocean noise impacts the detection range of underwater gliders, and environmental variables impact ambient noise levels. The goal of this study is to predict hourly ambient noise levels in five whale-call frequency bands from weather and sea state, and turning those levels into how far a glider can expect to hear.

**Team Members:**

Suramya Angdembay (University of Mississippi, Aquaview.org)

Kapil Sharma (University of Mississippi, Aquaview.org)

Bibas Kandel (University of Mississippi, Aquaview.org)

**Links:**

- [Updated Noise Nowcaster](https://github.com/imbishal7/GliderRodeo)

- [README.md](https://github.com/NMFS-PAM-Glider/hackathon-shared-repo/tree/main/noise-nowcaster)

```{=html}
<iframe src="https://storage.googleapis.com/aquaview-public-assets/glider-rodeo/noise-nowcaster-slides.html#1" width="100%" height="600px" style="border: none;"></iframe>
```
